/* Regenerates native-eject-glyphs.h: the Source info EJECT label as 8-bit coverage.
 * Liberation Sans 24px matches the RX3 MY SETTINGS MENU button lettering.
 *   cc generate-eject-label.c $(pkg-config --cflags --libs freetype2) -o /tmp/gen
 *   /tmp/gen /usr/share/fonts/truetype/liberation/LiberationSans-Regular.ttf "EJECT" > native-eject-glyphs.h
 */
#include <ft2build.h>
#include FT_FREETYPE_H
#include <stdio.h>
#include <string.h>
#define BW 504
#define BH 60
static unsigned char canvas[BH][BW];
int main(int argc,char **argv){
 FT_Library ft;FT_Face face;
 if(argc!=3||FT_Init_FreeType(&ft)||FT_New_Face(ft,argv[1],0,&face)){fprintf(stderr,"usage: %s FONT TEXT\n",argv[0]);return 1;}
 FT_Set_Pixel_Sizes(face,0,24);
 if(FT_Load_Char(face,'E',FT_LOAD_RENDER))return 1;
 int cap=face->glyph->bitmap_top,width=0;
 for(const char *p=argv[2];*p;p++){if(FT_Load_Char(face,*p,FT_LOAD_DEFAULT))return 1;width+=(face->glyph->advance.x>>6)+(p[1]?1:0);}
 /* Native lettering has 1px extra tracking; its capitals fill rows 22-38 of the 60px button. */
 int pen=(BW-width)/2,baseline=22+cap;
 for(const char *p=argv[2];*p;p++){
  if(FT_Load_Char(face,*p,FT_LOAD_RENDER))return 1;
  FT_GlyphSlot g=face->glyph;
  for(unsigned y=0;y<g->bitmap.rows;y++)for(unsigned x=0;x<g->bitmap.width;x++){
   int cx=pen+g->bitmap_left+(int)x,cy=baseline-g->bitmap_top+(int)y;
   if(cx>=0&&cx<BW&&cy>=0&&cy<BH){unsigned v=canvas[cy][cx]+g->bitmap.buffer[y*g->bitmap.pitch+x];canvas[cy][cx]=v>255?255:v;}
  }
  pen+=(g->advance.x>>6)+1;
 }
 int x0=BW,y0=BH,x1=-1,y1=-1;
 for(int y=0;y<BH;y++)for(int x=0;x<BW;x++)if(canvas[y][x]){if(x<x0)x0=x;if(x>x1)x1=x;if(y<y0)y0=y;if(y>y1)y1=y;}
 if(x1<0)return 1;
 printf("/* Generated by generate-eject-label.c, Liberation Sans 24px coverage. */\n");
 printf("#define RX3_SOURCE_LABEL_X %d\n#define RX3_SOURCE_LABEL_Y %d\n",x0,y0);
 printf("#define RX3_SOURCE_LABEL_W %d\n#define RX3_SOURCE_LABEL_H %d\n",x1-x0+1,y1-y0+1);
 printf("static const unsigned char source_eject_label[%d][%d]={\n",y1-y0+1,x1-x0+1);
 for(int y=y0;y<=y1;y++){printf("{");for(int x=x0;x<=x1;x++)printf("%d%s",canvas[y][x],x<x1?",":"");printf("},\n");}
 printf("};\n");
 return 0;
}
